version: "3.8"
services:
  ic_microservice:
    build: .
    image: &img ic_microservice
    environment: &env
      - PYTHONPATH=/microservice/
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - RESULT_BACKEND_URL=redis://redis
      - CLASSIFY_QUEUE=classify_queue
      - C_FORCE_ROOT=True
      - PIKA_AUTO_ACK=True
      - PIKA_INPUT_ROUTING_KEY=Classification.Classify
      - PIKA_OUTPUT_ROUTING_KEY=Classification.Results
      - PIKA_EXCHANGE_NAME=classification
      - PIKA_EXCHANGE_TYPE=direct
      - PIKA_INPUT_QUEUE_NAME='ic_microservice_input_queue'
      - PIKA_OUTPUT_QUEUE_NAME='ic_microservice_output_queue'
      - PIKA_RABBITMQ_HOST=rabbitmq
      - DEBUG_MODE=True
    entrypoint: /microservice/scripts/entrypoint_main.sh
    depends_on: &dep
      - rabbitmq
      - redis
    restart: always
    ports:
      - 1111:1111
    volumes:
      - ./microservice:/microservice/microservice

  celery:
    build: .
    image: *img
    entrypoint: /microservice/scripts/entrypoint_classifier.sh
    hostname: celery
    environment: *env
    depends_on: *dep
    links:
      - rabbitmq
      - redis
    ports:
      - 1112:1112
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest

  flower:
    image: mher/flower:0.9.4
    command: ["--broker=amqp://guest:guest@rabbitmq:5672//"]
    ports:
      - 5555:5555
    restart: unless-stopped
    depends_on:
      - rabbitmq
