version: '3.8'
services: 
    ic_microservice:
        build: .
        image: &img ic_microservice
        environment: &env
            - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
            - RESULT_BACKEND_URL=redis://redis
            - PIKA_AUTO_ACK=True
            - PIKA_DEFAULT_ROUTING_KEY=Classification.Classify
            - PIKA_EXCHANGE_NAME=classification_requests
            - PIKA_EXCHANGE_TYPE=direct
            - PIKA_IS_QUEUE_EXCLUSIVE=True
            - PIKA_QUEUE_NAME=''
            - PIKA_RABBITMQ_HOST=rabbitmq
            - VECTORISER_PATH=/microservice/vectoriser.vz
            - CLASSIFIER_PATH=/microservice/trained_classifiers/
            - PYTHONPATH=/microservice/
        entrypoint: /microservice/scripts/entrypoint_main.sh
        depends_on: &dep
            - rabbitmq
            - redis
        volumes: 
            - ./app:/microservice/app
        restart: always
    
    vectoriser_worker:
        build: .
        image: *img
        entrypoint: /microservice/scripts/entrypoint_vectoriser.sh
        environment: *env
        depends_on: *dep
        volumes: 
            - ./app:/microservice/app
    
#    classifier_worker:
#        build: .
#        image: *img
#        entrypoint: /microservice/entrypoint_classifier.sh
#        environment: *env
#        depends_on: *dep
#        volumes: 
#            - ./app:/microservice/app

    rabbitmq:
        image: rabbitmq:3-management
        ports: 
            - "5672:5672"
            - "15672:15672"
    
    redis:
        image: redis:latest
    
#    flower:
#        image: mher/flower:0.9.5
#        command: ["-A app.ms_celery.celery_app", "--url_prefix=flower", "--broker=amqp://guest:guest@localhost:5672//"]
#        ports:
#            - 5555:5555
#        restart: unless-stopped