version: '3.8'
services: 
    ic_microservice:
        build: .
        image: &img ic_microservice
        environment: &env
            - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
            - RESULT_BACKEND_URL=redis://redis
            - PIKA_AUTO_ACK=True
            - PIKA_DEFAULT_ROUTING_KEY=Classification.Classify
            - PIKA_EXCHANGE_NAME=classification_requests
            - PIKA_EXCHANGE_TYPE=direct
            - PIKA_IS_QUEUE_EXCLUSIVE=True
            - PIKA_QUEUE_NAME='ic_microservice_input_queue'
            - PIKA_RABBITMQ_HOST=rabbitmq
            - VECTORISER_PATH=/microservice/vectoriser.vz
            - CLASSIFIER_PATH=/microservice/trained_classifiers/
            - PYTHONPATH=/microservice/
            - VECTORISER_QUEUE=vectorise_queue
            - CLASSIFIER_QUEUE=classify_queue
        entrypoint: /microservice/scripts/entrypoint_main.sh
        depends_on: &dep
            - rabbitmq
            - redis
        volumes: 
            - ./app:/microservice/app
        restart: always
    
    vectoriser_worker:
        build: .
        image: *img
        entrypoint: /microservice/scripts/entrypoint_vectoriser.sh
        hostname: vectoriser_worker
        environment: *env
        depends_on: *dep
        volumes: 
            - ./app:/microservice/app
        links: 
            - rabbitmq
            - redis
    
    classifier_worker:
        build: .
        image: *img
        entrypoint: /microservice/scripts/entrypoint_classifier.sh
        hostname: classifier_worker
        environment: *env
        depends_on: *dep
        volumes: 
            - ./app:/microservice/app
        links: 
            - rabbitmq
            - redis

    rabbitmq:
        image: rabbitmq:3-management
        ports: 
            - "5672:5672"
            - "15672:15672"
    
    redis:
        image: redis:latest
    
    flower:
        image: mher/flower:0.9.4
        command: ["--broker=amqp://guest:guest@rabbitmq:5672//"]
        ports:
            - 5555:5555
        restart: unless-stopped
        depends_on:
            - rabbitmq